version: '3.7'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: docker/php-fpm
    image: php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    networks:
      - internal
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    image: nginx
    volumes:
      - ./:/var/www
      - ./storage/app/public/:/var/www/public/storage/
    ports:
      - "8001:80"
    depends_on:
      - php-fpm
    networks:
      - internal
  db:
    container_name: pgsql
    build: ./docker/pgsql
    image: pgsql
    ports:
      - "5434:5432"
    volumes:
      - ./docker/pgsql/init:/docker-entrypoint-initdb.d
      - ./docker/pgsql/pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal

  #db:
    #container_name: mysql
    #build: ./docker/mysql
    #image: mysql
    #ports:
      #- "3308:3306"
    #volumes:
      #- ./docker/mysql/init:/docker-entrypoint-initdb.d
      #- ./docker/mysql/mydata:/var/lib/mysql
    #environment:
      #- MYSQL_DB=${DB_DATABASE}
      #- MYSQL_USER=${DB_USERNAME}
      #- MYSQL_PASSWORD=${DB_PASSWORD}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
    #networks:
      #- internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
